export interface Torrent {
  added_on: number;
  amount_left: number;
  auto_tmm: boolean;
  availability: number;
  category: string;
  completed: number;
  completion_on: number;
  content_path: string;
  dl_limit: number;
  dlspeed: number;
  downloaded: number;
  downloaded_session: number;
  eta: number;
  f_l_piece_prio: boolean;
  force_start: boolean;
  hash: string;
  inactive_seeding_time_limit: number;
  infohash_v1: string;
  infohash_v2: string;
  last_activity: number;
  magnet_uri: string;
  max_inactive_seeding_time: number;
  max_ratio: number;
  max_seeding_time: number;
  name: string;
  num_complete: number;
  num_incomplete: number;
  num_leechs: number;
  num_seeds: number;
  priority: number;
  progress: number;
  ratio: number;
  ratio_limit: number;
  save_path: string;
  seeding_time: number;
  seeding_time_limit: number;
  seen_complete: number;
  seq_dl: boolean;
  size: number;
  state: TorrentState;
  super_seeding: boolean;
  tags: string;
  time_active: number;
  total_size: number;
  tracker: string;
  trackers_count: number;
  up_limit: number;
  uploaded: number;
  uploaded_session: number;
  upspeed: number;
}

export type TorrentState = 
  | 'allocating'
  | 'downloading'
  | 'metaDL'
  | 'pausedDL'
  | 'pausedUP'
  | 'queuedDL'
  | 'queuedUP'
  | 'stalledDL'
  | 'stalledUP'
  | 'uploading'
  | 'forcedDL'
  | 'forcedUP'
  | 'checkingDL'
  | 'checkingUP'
  | 'checkingResumeData'
  | 'error'
  | 'missingFiles'
  | 'unknown';

export interface GlobalTransferInfo {
  alltime_dl: number;
  alltime_ul: number;
  average_time_queue: number;
  connection_status: string;
  dht_nodes: number;
  dl_info_data: number;
  dl_info_speed: number;
  dl_rate_limit: number;
  free_space_on_disk: number;
  global_ratio: string;
  queued_io_jobs: number;
  queueing: boolean;
  read_cache_hits: string;
  read_cache_overload: string;
  refresh_interval: number;
  total_buffers_size: number;
  total_peer_connections: number;
  total_queued_size: number;
  total_wasted_session: number;
  up_info_data: number;
  up_info_speed: number;
  up_rate_limit: number;
  use_alt_speed_limits: boolean;
  write_cache_overload: string;
}

export interface TorrentInfo {
  addition_date: number;
  comment: string;
  completion_date: number;
  created_by: string;
  creation_date: number;
  dl_limit: number;
  dl_speed: number;
  dl_speed_avg: number;
  eta: number;
  hash: string;
  is_private: boolean;
  last_seen: number;
  name: string;
  nb_connections: number;
  nb_connections_limit: number;
  peers: number;
  peers_total: number;
  piece_size: number;
  pieces_have: number;
  pieces_num: number;
  reannounce: number;
  save_path: string;
  seeding_time: number;
  seeds: number;
  seeds_total: number;
  share_ratio: number;
  time_elapsed: number;
  total_downloaded: number;
  total_downloaded_session: number;
  total_size: number;
  total_uploaded: number;
  total_uploaded_session: number;
  total_wasted: number;
  tracker: string;
  trackers: string;
  up_limit: number;
  up_speed: number;
  up_speed_avg: number;
}

export interface Preferences {
  locale: string;
  create_subfolder_enabled: boolean;
  start_paused_enabled: boolean;
  auto_delete_mode: number;
  preallocate_all: boolean;
  incomplete_files_ext: boolean;
  auto_tmm_enabled: boolean;
  torrent_changed_tmm_enabled: boolean;
  save_path_changed_tmm_enabled: boolean;
  category_changed_tmm_enabled: boolean;
  save_path: string;
  temp_path_enabled: boolean;
  temp_path: string;
  scan_dirs: Record<string, number>;
  export_dir: string;
  export_dir_fin: string;
  mail_notification_enabled: boolean;
  mail_notification_sender: string;
  mail_notification_email: string;
  mail_notification_smtp: string;
  mail_notification_ssl_enabled: boolean;
  mail_notification_auth_enabled: boolean;
  mail_notification_username: string;
  mail_notification_password: string;
  autorun_enabled: boolean;
  autorun_program: string;
  queueing_enabled: boolean;
  max_active_downloads: number;
  max_active_torrents: number;
  max_active_uploads: number;
  dont_count_slow_torrents: boolean;
  slow_torrent_dl_rate_threshold: number;
  slow_torrent_ul_rate_threshold: number;
  slow_torrent_inactive_timer: number;
  max_ratio_enabled: boolean;
  max_ratio: number;
  max_ratio_act: number;
  listen_port: number;
  upnp: boolean;
  random_port: boolean;
  dl_limit: number;
  up_limit: number;
  max_connec: number;
  max_connec_per_torrent: number;
  max_uploads: number;
  max_uploads_per_torrent: number;
  stop_tracker_timeout: number;
  enable_piece_extent_affinity: boolean;
  bittorrent_protocol: number;
  limit_utp_rate: boolean;
  limit_tcp_overhead: boolean;
  limit_lan_peers: boolean;
  alt_dl_limit: number;
  alt_up_limit: number;
  scheduler_enabled: boolean;
  schedule_from_hour: number;
  schedule_from_min: number;
  schedule_to_hour: number;
  schedule_to_min: number;
  scheduler_days: number;
  dht: boolean;
  pex: boolean;
  lsd: boolean;
  encryption: number;
  anonymous_mode: boolean;
  proxy_type: number;
  proxy_ip: string;
  proxy_port: number;
  proxy_peer_connections: boolean;
  proxy_auth_enabled: boolean;
  proxy_username: string;
  proxy_password: string;
  proxy_torrents_only: boolean;
  ip_filter_enabled: boolean;
  ip_filter_path: string;
  ip_filter_trackers: boolean;
  web_ui_domain_list: string;
  web_ui_address: string;
  web_ui_port: number;
  web_ui_upnp: boolean;
  web_ui_username: string;
  web_ui_password: string;
  web_ui_csrf_protection_enabled: boolean;
  web_ui_clickjacking_protection_enabled: boolean;
  web_ui_secure_cookie_enabled: boolean;
  web_ui_max_auth_fail_count: number;
  web_ui_ban_duration: number;
  web_ui_session_timeout: number;
  web_ui_host_header_validation_enabled: boolean;
  bypass_local_auth: boolean;
  bypass_auth_subnet_whitelist_enabled: boolean;
  bypass_auth_subnet_whitelist: string;
  web_ui_https_enabled: boolean;
  web_ui_https_key_path: string;
  web_ui_https_cert_path: string;
  web_ui_use_custom_http_headers_enabled: boolean;
  web_ui_custom_http_headers: string;
  web_ui_reverse_proxy_enabled: boolean;
  web_ui_reverse_proxies_list: string;
  web_ui_use_custom_http_headers: boolean;
  alternative_webui_enabled: boolean;
  alternative_webui_path: string;
}